version: '3.8'

services:
  product-of-the-main-diagonal-of-a-square-matrix-typescript-app:
    container_name: product-of-the-main-diagonal-of-a-square-matrix-typescript
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9080:9080
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9080/health']
      interval: 10s
      timeout: 10m
      retries: 5
      start_period: 10s
